name: Sync LeetCode Submissions

on:
  workflow_dispatch: # Allows you to run it manually
  schedule:
    - cron: '0 8 * * *' # Runs automatically every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode Submissions
        uses: seasonss/leetcode-sync-v2@v1.0.1
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'solutions'
